Revert "Merge pull request #421 from kana/dependabot/npm_and_yarn/eslint-plugin-import-2.25.1"
This reverts commit 24d02d59d2de4ff05651c9f22daf66492da4ba54, reversing
changes made to db0106dc2dd930a8191da6da34dc7939e6696400.

For some reason, this update causes the following error.

```
$ yarn add eslint-module-utils
$ yarn run eslint --ext .js,.vue lib
yarn run v1.22.4
$ /Users/kana/working/hatokurandom/node_modules/.bin/eslint --ext .js,.vue lib

Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Cannot read property 'body' of undefined
Occurred while linting /Users/kana/working/hatokurandom/lib/eventbus.js:1
    at Object.isUnambiguousModule [as isModule] (/Users/kana/working/hatokurandom/node_modules/eslint-plugin-import/node_modules/eslint-module-utils/unambiguous.js:29:14)
    at Function.ExportMap.parse (/Users/kana/working/hatokurandom/node_modules/eslint-plugin-import/lib/ExportMap.js:790:454)
    at Function.ExportMap.for (/Users/kana/working/hatokurandom/node_modules/eslint-plugin-import/lib/ExportMap.js:787:201)
    at Function.ExportMap.get (/Users/kana/working/hatokurandom/node_modules/eslint-plugin-import/lib/ExportMap.js:781:463)
    at processBodyStatement (/Users/kana/working/hatokurandom/node_modules/eslint-plugin-import/lib/rules/namespace.js:49:52)
    at Array.forEach (<anonymous>)
    at Program (/Users/kana/working/hatokurandom/node_modules/eslint-plugin-import/lib/rules/namespace.js:81:18)
    at /Users/kana/working/hatokurandom/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/kana/working/hatokurandom/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
error Command failed with exit code 2.
```